demo:
    greeting:
         message: Hello, softuni!

#https://api:
#  frankfurter:
#    dev/v1/latest?base=EUR&symbols=BGN,USD,PLN:
frankfurter:
        schema: https
        host: api.frankfurter.dev
        path: /v1/latest
        symbols: BGN,USD,PLN
        enabled: true

jsonplaceholder:
    schema: https
    host: jsonplaceholder.typicode.com
    path: /posts/
    enabled: true

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor: TRACE
                SQL: DEBUG
            nodeValue: WARN
        blog: WARN