demo:
    greeting:
         message: Hello, softuni!
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        password: ${MYSQL_PASSWORD:1234}
        username: ${MYSQL_USERNAME:root}
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
            open-in-view: false
            properties:
            hibernate:
                format_sql: true

    sql:
        init:
            mode: never

    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/
        resources: # Static resources
            static-locations: file:src/main/resources/static/
            cache:
                period: 0
#https://api:
#  frankfurter:
#    dev/v1/latest?base=EUR&symbols=BGN,USD,PLN:
frankfurter:
        schema: https
        host: api.frankfurter.dev
        path: /v1/latest
        symbols: BGN,USD,PLN
        enabled: true

jsonplaceholder:
    schema: https
    host: jsonplaceholder.typicode.com
    path: /posts/
    enabled: true

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor: TRACE
                SQL: DEBUG
            nodeValue: WARN
        blog: WARN

server:
    port: 9999