spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${MYSQL_PASSWORD:}
    username: ${MYSQL_USERNAME:}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      open-in-view: false
      properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
  bikes:
    rememberMeKey: ${REMEMBER_ME_KEY:key}

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

logging:
  org:
    hibernate:
      type:
        descriptor: TRACE
      SQL: DEBUG
    nodeValue: WARN
  blog: WARN

server:
  port: 8080

frankfurter:
  schema: https
  host: api.frankfurter.dev
  path: /v1/latest
  symbols: BGN,USD,PLN
  enabled: false