
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/comments-server?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${MYSQL_PASSWORD:}
    username: ${MYSQL_USERNAME:}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true


  sql:
    init:
      mode: never

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: DEBUG
      nodeValue: WARN
      springframework.web: DEBUG
    blog: WARN
server:
  port: 6363